const products = [
    {
      '_id': '1',
      'name': 'ProConcealer',
      'image': '/images/concealer.jpg',
      'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 100.00,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Eyepencil',
      'image': '/images/eyepencil.jpg',
      'description':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 50.00,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'contour pallete',
      'image': '/images/eyeshadow.jpg',
      'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      'brand': 'Cannon',
      'category': 'Electronics',
      'price': 400.00,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Juvias Eyeshadow',
      'image': '/images/eyeshadow_juvias.jpg',
      'description':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      'brand': 'Sony',
      'category': 'Electronics',
      'price': 550.00,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Foundation',
      'image': '/images/foundation.jpg',
      'description':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      'brand': 'Logitech',
      'category': 'Electronics',
      'price': 400.00,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Highlighter',
      'image': '/images/highlighter.jpg',
      'description':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      'brand': 'Amazon',
      'category': 'Electronics',
      'price': 250.00,
      'countInStock': 0,
      'rating': 1,
      'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'lash glue',
        'image': '/images/lashglue.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 150.00,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
      {
        '_id': '8',
        'name': 'Lipstick',
        'image': '/images/lipstick.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 150.00,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
      {
        '_id': '9',
        'name': 'Sacha',
        'image': '/images/sacha.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 250.00,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
      {
        '_id': '10',
        'name': 'setting spray',
        'image': '/images/setting_spray.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 400.00,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
  ]
  
  